name: demo_firebase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gagionvuive.png
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/gagionvuive.png
  android_12:
    image: assets/gagionvuive.png
    color: "#FFFFFF"
